### PR TITLE
[1258] Add required libraries as dependencies when publishing a project

### LINKED ISSUE #1258: Library publication does not include project's dependencies
Steps to reproduce:
1. Create a SysML project with a PartDefinition "MyPartDefinition" in it
2. Publish the project
3. Create another SysML project
4. Import the library
5. Create a part in the project and set its type to "MyPartDefinition"
6. Publish the project
7. Open the library published from the second project
8. The library does not contain the dependency to the first project

### PR DESCRIPTION
**Pull request by gdaniel**
Bug: https://github.com/eclipse-syson/syson/issues/1258

Fixes #1258 

# PLEASE READ ALL ITEMS AND CHECK ONLY RELEVANT CHECKBOXES BELOW

## Project management

- [x] Has the pull request been added to the relevant milestone?
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `type:`)
- [x] Have the relevant issues been added to the same project milestone as the pull request?

## Changelog and release notes

- [x] Has the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] In case of a change with a visual impact, are there any screenshots in the `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] In case of a key change, has the change been added to `Key highlights` section in `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?

## Documentation

- [ ] Have you included an update of the [documentation](https://doc.mbse-syson.org) in your pull request? Please ask yourself if an update (installation manual, user manual, developer manual...) is needed and add one accordingly.

## Tests

- [x] Is the code properly tested? Any pull request (fix, enhancement or new feature) should come with a test (or several). It could be unit tests, integration tests or cypress tests depending on the context. Only doc and releng pull request do not need for tests.

### CODE REVIEW

File: backend/application/syson-application/src/test/java/org/eclipse/syson/application/libraries/publication/SySONLibraryPublicationTests.java [hunk 1]
```diff
@@ -10,7 +10,7 @@
  * Contributors:
  *     Obeo - initial API and implementation
  *******************************************************************************/
-package org.eclipse.syson.application.publication;
+package org.eclipse.syson.application.libraries.publication;
```
Comment (gdaniel) [inline backend/application/syson-application/src/test/java/org/eclipse/syson/application/libraries/publication/SySONLibraryPublicationTests.java:13]: I moved this test in `libraries/publication` to uniformize the package structure w.r.t. import and update
