### PR TITLE
[2143] Replace Path with String in library loading configuration

### LINKED ISSUE #2143: `Path` objects are incompatible with classpath resource resolution on Windows
### Description
When constructing a `locationPattern` for Spring's `PathMatchingResourcePatternResolver` in `SysONLibraryLoader` using a `Path` object (e.g., `Paths.get("name/library")`), the resulting path string contains **backslashes (`\`)** on Windows. This breaks resource resolution in JAR files and the classpath, as JARs and Spring's resource loaders **only accept forward slashes (`/`)** for paths.

### Current Behavior
- On **Windows**, `Paths.get("name", "library").toString()` returns `name\library`.
- When used in a `locationPattern` like `classpath*:name\library/*.json`, Spring fails to find the resource because:
  - JAR files internally use `/` as separators.
  - Spring's `PathMatchingResourcePatternResolver` expects `/` in classpath patterns.

### Expected Behavior
The `locationPattern` should always use `/` as a separator, regardless of the operating system, to ensure compatibility with:
- JAR files.
- Spring's resource resolution.
- Cross-platform deployments.

### PR DESCRIPTION
**Pull request by frouene**
Bug: https://github.com/eclipse-syson/syson/issues/2143

# PLEASE READ ALL ITEMS AND CHECK ONLY RELEVANT CHECKBOXES BELOW

## Auto review

- [x] Have you reviewed this PR? Please do a first quick review, It is very useful to detect typos and missing copyrights, check comments, check your code... The reviewer will thank you for that :)

## Project management

- [x] Has the pull request been added to the relevant milestone?
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `type:`)
- [x] Have the relevant issues been added to the same project milestone as the pull request?

## Changelog and release notes

- [ ] Has the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc` been updated to reference the relevant issues?
- [x] Have the relevant API breaks been described in the `CHANGELOG.adoc`?
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] In case of a change with a visual impact, are there any screenshots in the `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] In case of a key change, has the change been added to `Key highlights` section in `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?

## Documentation

- [ ] Have you included an update of the [documentation](https://doc.mbse-syson.org) in your pull request? Please ask yourself if an update (installation manual, user manual, developer manual...) is needed and add one accordingly.

## Tests

- [ ] Is the code properly tested? Any pull request (fix, enhancement or new feature) should come with a test (or several). It could be unit tests, integration tests or cypress tests depending on the context. Only doc and releng pull request do not need for tests.

### CODE REVIEW

**Comment by frouene** [comment]
I'm not sure if we need to add an entry to the user manual, it doesn't seem like a change that would affect end users.

**Comment by AxelRICHARD** [comment]
> I'm not sure if we need to add an entry to the user manual, it doesn't seem like a change that would affect end users.

No we don't need to add an entry to the user manual.

File: backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java [hunk 1]
```diff
@@ -61,11 +60,15 @@ public record SysONLibraryLoadingDefinition(
         Objects.requireNonNull(fileExtensions);
         Objects.requireNonNull(resourceLoadingBehavior);
 
-        if (relativePathToDirectoryContainingLibraryFiles.isAbsolute()) {
-            throw new IllegalArgumentException("Path '%s' is absolute, but a relative one was expected.".formatted(relativePathToDirectoryContainingLibraryFiles.toString()));
+        if (relativePathToDirectoryContainingLibraryFiles.startsWith("/")) {
+            throw new IllegalArgumentException("Path '%s' is absolute, but a relative one was expected.".formatted(relativePathToDirectoryContainingLibraryFiles));
         }
-        if (relativePathToDirectoryContainingLibraryFiles.toFile().exists() && !relativePathToDirectoryContainingLibraryFiles.toFile().isDirectory()) {
```
Comment (AxelRICHARD) [inline backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java:67]: I understand those APIs can't be used anymore because we don't use _Paths_ anymore, but still need to test that the path is a directory, right?
Could you find a way to still test that please?

File: backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /*******************************************************************************
- * Copyright (c) 2025 Obeo.
```
Comment (AxelRICHARD) [inline backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java:2]: Could you find a way to test your changes please?

File: backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java (hunk 1 above)
Comment (frouene) [reply backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java:67]: Actually, I don't think that test made much sense, because the path had to resolve a file without searching the classpath but directly on the file system, so I guess it never found the folder directly

File: backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java (hunk 2 above)
Comment (frouene) [reply backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java:2]: I thought about it, but it already exists `SysMLEditingContextProcessorTest#loadKerMLLibraries` and `SysMLEditingContextProcessorTest#loadSysMLLibraries` that do exactly what I need.

File: backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java (hunk 1 above)
Comment (AxelRICHARD) [reply backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java:67]: ok

File: backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java (hunk 2 above)
Comment (AxelRICHARD) [reply backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java:2]: yes but what happens with a path containing / or \ ? It seems not tested in `SysMLEditingContextProcessorTest`

Comment (frouene) [reply backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java:2]: 👍 I added some test about the definition

Comment (AxelRICHARD) [reply backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java:2]: Great, thank you!

**Review by AxelRICHARD — APPROVED** [review]
