### PR TITLE
[1487] Fix NPE thrown by getTreePath on non-view explorers

### LINKED ISSUE #1487: NPE in SysONExplorerTreePathProvider for explorers that aren't defined with the view DSL
The method `SysONExplorerTreePathProvider#canHandle` does not check if the `sourceId` parameter list is `null`, which is the case for explorers that aren't defined with the view DSL.

```java
@Override
public boolean canHandle(Tree tree) {
    if (tree != null) {
        var sysonExplorerId = UUID.nameUUIDFromBytes(SysONExplorerTreeDescriptionProvider.SYSON_EXPLORER.getBytes()).toString();
        var parameters = this.urlParser.getParameterValues(tree.getDescriptionId());
        // parameters can be null here
        var sourceId = parameters.get("sourceId").get(0);
        return Objects.equals(sysonExplorerId, sourceId);
    }
    return false;
}
```

This can create NPE in downstream applications that rely on description-level explorers.

### PR DESCRIPTION
**Pull request by gdaniel**
Bug: https://github.com/eclipse-syson/syson/issues/1487

Fixes #1487

# PLEASE READ ALL ITEMS AND CHECK ONLY RELEVANT CHECKBOXES BELOW

## Project management

- [x] Has the pull request been added to the relevant milestone?
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `type:`)
- [x] Have the relevant issues been added to the same project milestone as the pull request?

## Changelog and release notes

- [x] Has the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] In case of a change with a visual impact, are there any screenshots in the `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] In case of a key change, has the change been added to `Key highlights` section in `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?

## Documentation

- [ ] Have you included an update of the [documentation](https://doc.mbse-syson.org) in your pull request? Please ask yourself if an update (installation manual, user manual, developer manual...) is needed and add one accordingly.

## Tests

- [x] Is the code properly tested? Any pull request (fix, enhancement or new feature) should come with a test (or several). It could be unit tests, integration tests or cypress tests depending on the context. Only doc and releng pull request do not need for tests.

### CODE REVIEW

File: backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/view/SysONExplorerTests.java [hunk 1]
```diff
@@ -307,7 +327,7 @@ public void getContextMenuOfModelAndLibraryDirectories() {
         assertThat(sysmlDirectoryContextMenu).isEmpty();
     }
 
-    @DisplayName("GIVEN an empty SysML Project, WHEN context menu is queried, THEN the tree path should take into accounts the Explorer filters.")
```
Comment (gdaniel) [inline backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/view/SysONExplorerTests.java:310]: I removed the "context menu" part, since the test does not check the context menu

File: CHANGELOG.adoc [hunk 2]
```diff
@@ -11,6 +11,8 @@
 === Bug fixes
 
 - https://github.com/eclipse-syson/syson/issues/1454[#1454] [import] Fix an issue where importing textual models with `MetadataAccessExpression` failed.
+- https://github.com/eclipse-syson/syson/issues/1487[#1487] [explorer] Fix NPE thrown by `getTreePath` on non-view explorers.
```
Comment (AxelRICHARD) [inline CHANGELOG.adoc]: non-view explorers => may be something like 
Explorers defined with Sirius Tree APIs instead of Sirius View DSL APIs
What do you think about ? If you are ok with that, please fix it everywhere in this PR.

File: backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONExplorerTreePathProvider.java [hunk 3]
```diff
@@ -68,13 +68,17 @@ public SysONExplorerTreePathProvider(ITreeNavigationService treeNavigationServic
...
     public boolean canHandle(Tree tree) {
+        boolean result = false;
         if (tree != null) {
             var sysonExplorerId = UUID.nameUUIDFromBytes(SysONExplorerTreeDescriptionProvider.SYSON_EXPLORER.getBytes()).toString();
             var parameters = this.urlParser.getParameterValues(tree.getDescriptionId());
-            var sourceId = parameters.get("sourceId").get(0);
-            return Objects.equals(sysonExplorerId, sourceId);
+            var sourceIdParameter = parameters.get("sourceId");
+            if (sourceIdParameter != null && !sourceIdParameter.isEmpty()) {
+                var sourceId = parameters.get("sourceId").get(0);
```
Comment (AxelRICHARD) [inline backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONExplorerTreePathProvider.java]: parameters.get("sourceId") => sourceIdParameter

File: CHANGELOG.adoc (hunk 2 above)
Comment (gdaniel) [reply CHANGELOG.adoc]: Sure, it is clearer than "non-view explorers". I have changed it (including in the description of the commit).

File: backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONExplorerTreePathProvider.java (hunk 3 above)
Comment (gdaniel) [reply backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONExplorerTreePathProvider.java]: Done

**Review by AxelRICHARD — APPROVED** [review]
