### PR TITLE
[1166] Ensure current library is at library workbench explorer's root

### LINKED ISSUE #1166: Published libraries containing a LibraryPackage are not displayed correctly in the Explorer view
To reproduce:
1. Create a SysML project with a LibraryPackage as one of its "root" elements
2. Publish it as a library
3. In the list of libraries, open the library to see it in the editor
4. The contents of the libraries are displayed under node Libraries > User libraries => KO
The contents of the libraries should instead be displayed at the root of the Explorer view.

`SysONResourceService.sFromReferencedLibrary(Resource)` relies on the presence of LibraryMetadataAdapter on the Resource.
This adapter is created by Sirius Web when loading the dependencies of a project (`org.eclipse.sirius.web.application.editingcontext.services.EditingContextDependencyLoader.loadDependencies(IEditingContext)`) and when loading a SemanticData (`org.eclipse.sirius.web.application.editingcontext.services.EditingContextLoader.loadSemanticData(EditingContext, SemanticData)`).

I think the issue is due to the latter. I'm not sure if this is an issue we need to fix in Sirius Web or if we need our SysON calls to provide additional context (or do another check) to check whether our Resource is from the semantic data being edited in our context.

### PR DESCRIPTION
**Pull request by gdaniel**
Fixes #1166
Based on #1651 (to avoid conflicts on the services moved to `syson-tree-services`)

# PLEASE READ ALL ITEMS AND CHECK ONLY RELEVANT CHECKBOXES BELOW

## Project management

- [x] Has the pull request been added to the relevant milestone?
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `type:`)
- [x] Have the relevant issues been added to the same project milestone as the pull request?

## Changelog and release notes

- [x] Has the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc` been updated to reference the relevant issues?
- [x] Have the relevant API breaks been described in the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] In case of a change with a visual impact, are there any screenshots in the `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] In case of a key change, has the change been added to `Key highlights` section in `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?

## Documentation

- [ ] Have you included an update of the [documentation](https://doc.mbse-syson.org) in your pull request? Please ask yourself if an update (installation manual, user manual, developer manual...) is needed and add one accordingly.

## Tests

- [x] Is the code properly tested? Any pull request (fix, enhancement or new feature) should come with a test (or several). It could be unit tests, integration tests or cypress tests depending on the context. Only doc and releng pull request do not need for tests.

### CODE REVIEW

File: backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/SysONResourceServiceTests.java [hunk 1]
```diff
@@ -54,16 +75,80 @@ public void setUpResources() {
...
+        assertThat(this.sysONResourceService.isFromReferencedLibrary(this.editingContext, this.resourceWithImportedElement)).isFalse();
+        assertThat(this.sysONResourceService.isFromReferencedLibrary(this.editingContext, this.resourceWithLibraryMetadataMatchingEditingContext)).isFalse();
+    }
+
+    /**
+     * A mock editing context used to test {@link SysONResourceService}
+     *
+     * @author gdaniel
+     */
+    private static final class MockEditingContext implements IEditingContext {
```
Comment (gdaniel) [inline backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/SysONResourceServiceTests.java:96]: We need these mock classes to be able to unit test `SysONResourceServiceTest`.

File: backend/services/syson-tree-services/src/main/java/org/eclipse/syson/tree/explorer/filters/HideUserLibrariesTreeAlteredContentProvider.java [hunk 2]
```diff
@@ -42,6 +48,13 @@ public boolean canHandle(IEditingContext editingContext, List<String> activeFilt
 
     @Override
     public List<Object> apply(List<Object> computedElements, VariableManager variableManager) {
-        return this.filterService.hideUserLibraries(computedElements);
+        List<Object> result = new ArrayList<>();
+        Optional<IEditingContext> optionalEditingContext = variableManager.get("editingContext", IEditingContext.class);
```
Comment (AxelRICHARD) [inline backend/services/syson-tree-services/src/main/java/org/eclipse/syson/tree/explorer/filters/HideUserLibrariesTreeAlteredContentProvider.java]: "editingContext" => IEditingContext.EDITING_CONTEXT

File: doc/content/modules/user-manual/pages/release-notes/2025.12.0.adoc [hunk 3]
```diff
@@ -175,6 +175,9 @@ part p2 :> p1 {
 }
 ```
 
+- Fix an issue that made the explorer display libraries with only `LibraryPackage` top-level element under the `User libraries` directory in the library workbench.
```
Comment (AxelRICHARD) [inline doc/content/modules/user-manual/pages/release-notes/2025.12.0.adoc]: explorer => _Explorer_ view
