### PR TITLE
[1090] Fix the import of MultiplicityRange with lower and upper bounds

### LINKED ISSUE #1090: SysML textual import of multiplicitpy including `..` is not supported
### Description

If user try to import syml textual file including elements with multiplicity `..` (ex.: [0..2]), the import ignores it and does not create associated `literalInteger` in the model. 
There are no problems with import if multiplicity does not include `..` (ex.: [2]) Besides, SysON support management of multiplicity with `..` (ex.: [0..2]). You can check it by direct edit an element and typing `[0..2]`, two `LiteralInteger` are created. 

Image

### Use case for reproduction: 

Import the following sysml textual file:
```
package LibraryPackage1 {
	item def Engines;
	item def Ariane6 {
		item engines : Engines [0..2];
	}
}
```

### PR DESCRIPTION
**Pull request by gdaniel**
SysIDE does a bad job at parsing multiplicity ranges with upper and lower bounds: it produces a `MultiplicityRange` with an  `OperatorExpression` containing features ultimately containing `LiteralIntegers`, while the specification (and the pilot implementation) indicate to create a `MultiplicityRange` containing directly the `LiteralIntegers`.

Similarly, SysIDE creates `FeatureChainExpression` and `FeatureChaining` inside the `OperatorExpression` for bounds that refer to a `Feature`, while the specification indicate to create a `FeatureReferenceExpression` with a referent to the `Feature`.

Note that in this second case the pilot implementation does not implement the specification, and it is not possible to have `Feature` as upper and lower bounds of a `MultiplicityRange`.

The fix is implemented in the _post resolving fixing phase_ of the import, because it needs to access the features effectively referenced by the produced `FeatureChainExpression`. We can't manipulate proxies because the resolution of `FeatureChainExpression` is not the same as the resolution of `FeatureReferenceExpression`:  a proxy used in the context of a `FeatureChainExpression` can't be resolved as is in the context of a `FeatureReferenceExpression`.

I think it could be a good idea to have @adaussy take an additional look at this pull request, as it touches core parts of the import mechanism and I am not sure I understand all the implications of it.

Fixes #1090 

# PLEASE READ ALL ITEMS AND CHECK ONLY RELEVANT CHECKBOXES BELOW

## Project management

- [x] Has the pull request been added to the relevant milestone?
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `type:`)
- [x] Have the relevant issues been added to the same project milestone as the pull request?

## Changelog and release notes

- [x] Has the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] In case of a change with a visual impact, are there any screenshots in the `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] In case of a key change, has the change been added to `Key highlights` section in `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?

## Documentation

- [ ] Have you included an update of the [documentation](https://doc.mbse-syson.org) in your pull request? Please ask yourself if an update (installation manual, user manual, developer manual...) is needed and add one accordingly.

## Tests

- [x] Is the code properly tested? Any pull request (fix, enhancement or new feature) should come with a test (or several). It could be unit tests, integration tests or cypress tests depending on the context. Only doc and releng pull request do not need for tests.

### CODE REVIEW

File: backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java [hunk 1]
```diff
@@ -91,6 +93,54 @@ public Resource convertResource(final InputStream input, final ResourceSet resou
...
+            Element owner = operatorExpression.getOwner();
+            if (owner != null) {
+                for (Feature parameter : operatorExpression.getParameter()) {
+                    Expression parameterValue = parameter.getValuation().getValue();
+                    // Only LiteralExpressions and FeatureReferenceExpressions can be used in a MultiplicityRange
+                    if (parameterValue instanceof LiteralExpression || parameterValue instanceof FeatureReferenceExpression) {
+                        OwningMembership newOwningMembership = SysmlFactory.eINSTANCE.createOwningMembership();
+                        owner.getOwnedRelationship().add(newOwningMembership);
+                        newOwningMembership.getOwnedRelatedElement().add(parameterValue);
+                    } else if (parameterValue instanceof FeatureChainExpression featureChainExpression) {
```
Comment (adaussy) [inline backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java:120]: See comment in the test but I think this case does not happen.

**Review by adaussy — CHANGES_REQUESTED** [review]

File: backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java [hunk 2]
```diff
@@ -91,6 +93,54 @@ public Resource convertResource(final InputStream input, final ResourceSet resou
...
         for (EObject root : rootSysmlObjects) {
             this.fixTransitionUsageImplicitSource(root);
+            this.fixOperatorExpressionUsedAsRanges(root);
+        }
+    }
+
+    private void fixOperatorExpressionUsedAsRanges(EObject root) {
+        // Only get the OperatorExpressions used in MultiplicityRange. Based on KerML 8.2.5.8.1 OperatorExpression
+        // referring to the ".." function can exist, but the specification does not allow them in MultiplicityRange (see
+        // SysML 8.2.2.6.6 and KerML 8.2.5.11).
```
[the remark this answers is not in the document]
Comment (gdaniel) [reply backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java:173]: Done
https://github.com/sensmetry/sysml-2ls/issues/16

File: backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java [hunk 3]
```diff
@@ -638,6 +641,89 @@ public void checkAttributeUsageLiteralStringValueTest() throws IOException {
...
+                    .isInstanceOf(AttributeUsage.class)
+                    .returns("lower", Feature::getName);
+            assertThat(multiplicityRange.getUpperBound()).isInstanceOf(FeatureReferenceExpression.class);
+            FeatureReferenceExpression multiplicityRangeUpperBound = (FeatureReferenceExpression) multiplicityRange.getUpperBound();
+            assertThat(multiplicityRangeUpperBound.getReferent())
+                    .isInstanceOf(AttributeUsage.class)
+                    .returns("upper", Feature::getName);
+        }).check(input);
+    }
+
```
[the remark this answers is not in the document]
Comment (gdaniel) [reply backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java:730]: I added a test that works with LiteralInteger bounds, but it doesn't work with FeatureReferenceExpressions. Something goes wrong in the deresolution process and the multiplicity does not contain the qualified names of the bounds.
I quickly checked if there was an easy fix for that but couldn't find it.

File: backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java [hunk 4]
```diff
@@ -91,6 +93,54 @@ public Resource convertResource(final InputStream input, final ResourceSet resou
...
+        List<OperatorExpression> operatorExpressions = EMFUtils.allContainedObjectOfType(root, MultiplicityRange.class)
+                .flatMap(multiplicityRange -> multiplicityRange.getOwnedMember().stream())
+                .filter(OperatorExpression.class::isInstance)
+                .map(OperatorExpression.class::cast)
+                .filter(operatorExpression -> Objects.equals(operatorExpression.getOperator(), ".."))
+                .toList();
+        for (OperatorExpression operatorExpression : operatorExpressions) {
+            Element owner = operatorExpression.getOwner();
+            if (owner != null) {
```
[the remark this answers is not in the document]
Comment (gdaniel) [reply backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java]: I agree `owner` should never be null in this context, I removed it.

File: backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java [hunk 5]
```diff
@@ -638,6 +641,89 @@ public void checkAttributeUsageLiteralStringValueTest() throws IOException {
...
+        // KerML 8.3.4.11.2).
+        var input = """
+                part bounds {
+                    attribute lower:ScalarValues::Integer = 1;
+                    part upperBounds {
+                        attribute upper:ScalarValues::Integer = 2;
+                    }
+                }
+
+                part myPart[bounds.lower..bounds.upperBounds.upper];
```
[the remark this answers is not in the document]
Comment (gdaniel) [reply backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java]: Indeed, I mistakenly thought qualified names could have the dot pattern, but it is not the case.

File: backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java (hunk 1 above)
Comment (gdaniel) [reply backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java]: I removed this part

File: CHANGELOG.adoc [hunk 6]
```diff
@@ -40,6 +40,8 @@ When creating a new `Perform Action` referencing an existing `Action`, all compa
 - https://github.com/eclipse-syson/syson/issues/1300[#1300] [general-view] Fix wrong tool section name found in some compartments' palette.
 - https://github.com/eclipse-syson/syson/issues/1303[#1303] [general-view] Fix the name of `Constraint` creation tools inside `Requirement`.
 - https://github.com/eclipse-syson/syson/issues/1324[#1324] [details] Fix an issue that prevents ending up with a `null` reference in the reference widget.
+- https://github.com/eclipse-syson/syson/issues/1090[#1090] [import] Fix the import of MultiplicityRange with lower and upper bounds.
```
Comment (AxelRICHARD) [inline CHANGELOG.adoc:43]: MultiplicityRange => `MultiplicityRange`
import => textual import

File: backend/application/syson-sysml-import/pom.xml [hunk 7]
```diff
@@ -84,6 +84,11 @@
 			<version>2025.4.5</version>
 			<scope>test</scope>
 		</dependency>
+		<dependency>
```
Comment (AxelRICHARD) [inline backend/application/syson-sysml-import/pom.xml:87]: Please update the version.
Please move it before tests dependencies.

File: doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc [hunk 8]
```diff
@@ -39,6 +39,8 @@ They are now named:
 * `New Assume constraint`
 
 - In the _Details_ view, fix an issue that prevents opening the candidates on a reference widget.
+- Fix an issue in the textual import of MultiplicityRange with explicit lower and upper bounds.
```
Comment (AxelRICHARD) [inline doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc:42]: MultiplicityRange => `MultiplicityRange`

File: doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc [hunk 9]
```diff
@@ -39,6 +39,8 @@ They are now named:
...
+The import now correctly creates a `MultiplicityRange` containing `LiteralInteger` elements for integer bounds, and `FeatureReferenceExpression` elements for feature bounds.
```
Comment (AxelRICHARD) [inline doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc:43]: import => textual import

File: doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc (hunk 8 above)
Comment (gdaniel) [reply doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc]: done

File: backend/application/syson-sysml-import/pom.xml (hunk 7 above)
Comment (gdaniel) [reply backend/application/syson-sysml-import/pom.xml]: done

File: CHANGELOG.adoc (hunk 6 above)
Comment (gdaniel) [reply CHANGELOG.adoc]: done
